# Generated by Django 4.2.19 on 2025-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
